from setuptools import setup, find_packages

setup(
    name="code-refactoring-framework",
    version="1.0.0",
    description="AI-Powered Code Refactoring Framework using Transformers and Genetic Algorithms",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Research Team",
    author_email="research@example.com",
    url="https://github.com/research/code-refactoring-framework",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "peft>=0.4.0",
        "datasets>=2.12.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "ast-tools>=0.1.2",
        "pylint>=2.17.0",
        "radon>=6.0.0",
        "lizard>=1.17.0",
        "PyYAML>=6.0",
        "tqdm>=4.65.0",
        "wandb>=0.15.0",
        "plotly>=5.14.0",
        "networkx>=3.1",
        "tree-sitter>=0.20.0",
        "tree-sitter-python>=0.20.0",
        "deap>=1.3.3",
        "joblib>=1.2.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.0",
            "black>=23.3.0",
            "flake8>=6.0.0",
            "mypy>=1.3.0",
            "pre-commit>=3.3.0",
        ],
        "gpu": [
            "torch[cuda]>=2.0.0",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords="code refactoring, machine learning, transformers, genetic algorithms",
    entry_points={
        "console_scripts": [
            "refactor-code=refactoring.refactoring_engine:main",
            "generate-synthetic-data=data.synthetic_generator:main",
            "train-models=scripts.train_models:main",
        ],
    },
)